// Generated by CoffeeScript 1.6.3
var outcome, stepc, vine;

outcome = require("outcome");

stepc = require("stepc");

vine = require("vine");

exports.require = ["http.server", "npm.search"];

exports.load = function(httpServer, npmSearch) {
  /*
  
    /api/plugins/stats.json
    /api/plugins?q=search
  */

  httpServer.get("/api/plugins.json", function(req, res) {
    var count, kw, o, page, q;
    q = req.query.q;
    page = Number(req.query.page || 0);
    count = Number(req.query.count || 100);
    kw = new RegExp(q);
    q = {
      $or: [
        {
          keywords: kw
        }, {
          name: kw
        }
      ]
    };
    o = outcome.e(function(err) {
      return res.send(vine.error(err));
    });
    return stepc.async(function() {
      return npmSearch.search(q, this);
    }, o.s(function(items) {
      var end, start;
      start = page * count;
      end = start + count;
      return res.send(vine.result(items.slice(start, end)));
    }));
  });
  /*
  */

  return httpServer.get("/api/keywords.json", function(req, res) {
    var count, page;
    page = Number(req.query.page || 0);
    count = Number(req.query.count || 100);
    return npmSearch.keywords(function(err, keywords) {
      var end, start;
      start = page * count;
      end = start + count;
      return res.send(vine.result(keywords.slice(start, end)));
    });
  });
};
