// Generated by CoffeeScript 1.6.3
(function() {
  var MainView;

  MainView = require("./views/main");

  exports.require = ["http.server", "paperclip", "express", "browserify-middleware"];

  exports.load = function(httpServer, pc, express, browserify) {
    httpServer.engine("pc", pc.adapters.express);
    httpServer.set("views", __dirname + "/views");
    httpServer.get("/", function(req, res) {
      var view,
        _this = this;
      view = new MainView({
        routes: {
          pages: "home"
        }
      });
      return view.render(function() {
        return res.send(view.section.toString());
      });
    });
    httpServer.get("/plugins", function(req, res) {
      var view,
        _this = this;
      view = new MainView({
        routes: {
          pages: "plugins"
        }
      });
      return view.render(function() {
        return res.send(view.section.toString());
      });
    });
    httpServer.get("/js/plugins.bundle.js", browserify(__dirname + "/public/js/plugins/index.js"));
    httpServer.get("/js/home.bundle.js", browserify(__dirname + "/public/js/home/index.js"));
    return httpServer.use(express["static"](__dirname + "/public"));
  };

}).call(this);
