// Generated by CoffeeScript 1.6.3
(function() {
  var PluginsView, mojo, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  mojo = require("mojojs");

  PluginsView = (function(_super) {
    __extends(PluginsView, _super);

    function PluginsView() {
      _ref = PluginsView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    PluginsView.prototype.paper = require("./index.pc");

    return PluginsView;

  })(mojo.View);

  module.exports = PluginsView;

}).call(this);
