// Generated by CoffeeScript 1.6.3
var NPMSearch, flatstack, request, sift, type,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

flatstack = require("flatstack");

request = require("request");

sift = require("sift");

type = require("type-component");

NPMSearch = (function() {
  /*
  */

  function NPMSearch() {
    this.all = __bind(this.all, this);
    this.load = __bind(this.load, this);
    this._callstack = flatstack();
    this._modules = [];
    this.load();
    setInterval(this.load, 1000 * 60 * 10);
  }

  /*
  */


  NPMSearch.prototype.load = function() {
    var req,
      _this = this;
    console.log("loading mojo modules");
    return req = request.get({
      url: "http://registry.npmjs.org/-/all",
      json: true
    }, function(err, response, body) {
      var module, moduleName, modules;
      modules = [];
      for (moduleName in body) {
        module = body[moduleName];
        if (typeof module !== "object") {
          continue;
        }
        modules.push(body[moduleName]);
      }
      _this._modules = modules.filter(function(module) {
        if (!module.keywords || type(module.keywords) !== "array") {
          return false;
        }
        return ~module.keywords.indexOf("mojo-plugin");
      });
      return console.log("loaded %d mojo modules", _this._modules.length);
    });
  };

  /*
  */


  NPMSearch.prototype.search = function(query, next) {
    return next(null, sift(query)(this._modules || []));
  };

  /*
  */


  NPMSearch.prototype.all = function(next) {
    var _this = this;
    return this._callstack.push(function() {
      return next(null, _this._modules);
    });
  };

  return NPMSearch;

})();

exports.load = function() {
  return new NPMSearch();
};
