// Generated by CoffeeScript 1.6.3
(function() {
  var express;

  express = require("express");

  exports.require = ["config"];

  exports.load = function(config) {
    var p, server;
    server = express();
    server.listen(p = config.get("http.port"));
    console.log("HTTP server listening on port %d", p);
    return server;
  };

}).call(this);
