// Generated by CoffeeScript 1.6.3
var bindable, packages;

packages = require("packages");

bindable = require("bindable");

packages().require({
  config: new bindable.Object({
    http: {
      port: process.env.PORT || 8080
    }
  })
}).require(__dirname + "/packages").load();

