// Generated by CoffeeScript 1.6.3
var ContentView, mojo, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

mojo = require("mojojs");

ContentView = (function(_super) {
  __extends(ContentView, _super);

  function ContentView() {
    _ref = ContentView.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  ContentView.prototype.paper = require("./index.pc");

  return ContentView;

})(mojo.View);

module.exports = ContentView;

