// Generated by CoffeeScript 1.6.3
(function() {
  var MainView, mojo;

  MainView = require("./views/main");

  mojo = require("mojojs");

  exports.require = ["http.server", "paperclip", "express", "browserify-middleware"];

  exports.load = function(httpServer, pc, express, browserify) {
    var app;
    httpServer.set("views", __dirname + "/views");
    app = new mojo.Application();
    httpServer.get("/", function(req, res) {
      var view;
      view = new MainView({
        routes: {
          pages: "home"
        }
      }, app);
      return res.send(view.render().toString());
    });
    httpServer.get("/plugins", function(req, res) {
      var view;
      view = new MainView({
        routes: {
          pages: "plugins"
        }
      }, app);
      return res.send(view.render().toString());
    });
    httpServer.get("/js/plugins.bundle.js", browserify(__dirname + "/public/js/plugins/index.js"));
    httpServer.get("/js/home.bundle.js", browserify(__dirname + "/public/js/home/index.js"));
    return httpServer.use(express["static"](__dirname + "/public"));
  };

}).call(this);
