// Generated by CoffeeScript 1.6.3
(function() {
  var MainView, fs, mojo, pc, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  mojo = require("mojojs");

  fs = require("fs");

  pc = require("paperclip");

  MainView = (function(_super) {
    __extends(MainView, _super);

    function MainView() {
      _ref = MainView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    MainView.prototype.paper = require("./index.pc");

    MainView.prototype.sections = {
      pages: require("./pages")
    };

    return MainView;

  })(mojo.View);

  module.exports = MainView;

}).call(this);
