// Generated by CoffeeScript 1.6.3
(function() {
  exports.require = ["http.server", "express"];

  exports.load = function(httpServer, express) {
    return httpServer.use("/docs", express["static"](__dirname + "/../../../node_modules/mojo-docs/docs"));
  };

}).call(this);
